apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterissuer.name }}
  namespace: {{ .Values.namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: boralekc@gmail.com
    privateKeySecretRef:
      name: {{ .Values.clusterissuer.host }}
    solvers:
    - http01:
        ingress:
          class: nginx