name: Infrastructure workflow

on:
  push:
    tags:
      - terraform-*

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      working-directory: '${{ github.workspace }}'
      secrets.YC_SA_JSON_CREDENTIALS: 
    defaults:
      run:
        working-directory: ${{ env.working-directory }}/terraform
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.0
      
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Initialize Terraform
      run: terraform init -input=false -backend-config="access_key=${{ secrets.SPACE_ACCESS_KEY }}" -backend-config="secret_key=${{ secrets.SPACE_SECRET_KEY }}"

    - name: View terrafrom providers
      run: terraform providers

    - name: Plan Terraform changes
      run: terraform plan -input=false -var="TOKEN=${{ secrets.TOKEN }}" -var="SPACE_ACCESS_KEY=${{ secrets.SPACE_ACCESS_KEY }}" -var="SPACE_SECRET_KEY=${{ secrets.SPACE_SECRET_KEY }}" -var="DB_DEUTSCHHUB=${{ secrets.DB_DEUTSCHHUB }}" -var="DB_DEUTSCHLERN=${{ secrets.DB_DEUTSCHLERN }}"

    - name: Apply Terraform changes
      run: terraform apply --auto-approve -var="TOKEN=${{ secrets.TOKEN }}" -var="SPACE_ACCESS_KEY=${{ secrets.SPACE_ACCESS_KEY }}" -var="SPACE_SECRET_KEY=${{ secrets.SPACE_SECRET_KEY }}" -var="DB_DEUTSCHHUB=${{ secrets.DB_DEUTSCHHUB }}" -var="DB_DEUTSCHLERN=${{ secrets.DB_DEUTSCHLERN }}"